version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:16
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
      - "443:8443"
    environment:
      - KEYCLOAK_ENABLE_TLS=true
      - KEYCLOAK_TLS_KEYSTORE_FILE=/opt/bitnami/keycloak/certs/keystore.jks
      - KEYCLOAK_TLS_KEYSTORE_PASSWORD=secret
      - KEYCLOAK_TLS_TRUSTSTORE_FILE=/opt/bitnami/java/lib/security/cacerts
      - KEYCLOAK_TLS_TRUSTSTORE_PASSWORD=changeit
    volumes:
      - ./keystore.jks:/opt/bitnami/keycloak/certs/keystore.jks

volumes:
  postgresql_data:
    driver: local
